// Generated by CoffeeScript 1.6.1
(function() {
  var originalCollection, originalModel, originalSync;

  originalSync = Backbone.sync;

  originalModel = Backbone.Model.prototype.constructor;

  originalCollection = Backbone.Model.prototype.constructor;

  Backbone.sync = function(method, model, options) {
    var error, socket, success, _ref;
    socket = model.socket || ((_ref = model.collection) != null ? _ref.socket : void 0);
    if (!socket) {
      return originalSync.apply(this, arguments);
    }
    success = options.success;
    delete options.success;
    error = options.error;
    delete options.error;
    socket.emit("sync", {
      url: model.url(),
      method: method,
      model: JSON.stringify(model.toJSON()),
      options: options
    }, function(err, response) {
      if (err) {
        error.call(this, err);
      } else {
        success.apply(this, response);
      }
    });
  };

  Backbone.Model = Backbone.Model.extend({
    constructor: function(attributes, options) {
      this.socket = options != null ? options.socket : void 0;
      delete options.socket;
      originalModel.apply(this, arguments);
    }
  });

  Backbone.Collection = Backbone.Collection.extend({
    constructor: function(attributes, options) {
      this.socket = options != null ? options.socket : void 0;
      delete options.socket;
      originalCollection.apply(this, arguments);
    }
  });

}).call(this);
