// Generated by CoffeeScript 1.3.1
(function() {
  var originalSync;

  originalSync = Backbone.sync;

  Backbone.sync = function(method, model, options) {
    var error, socket, success, _ref;
    socket = model.socket || ((_ref = model.collection) != null ? _ref.socket : void 0);
    if (!socket) {
      originalSync.apply(this, arguments);
    }
    success = options.success;
    delete options.success;
    error = options.error;
    delete options.error;
    socket.emit("sync", {
      url: model.url(),
      method: method,
      model: JSON.stringify(model.toJSON()),
      options: options
    }, function(err, response) {
      if (err) {
        error.call(this, err);
      } else {
        success.apply(this, response);
      }
    });
  };

  this.SocketIOModel = Backbone.Model.extend({
    constructor: function(attributes, options) {
      this.socket = attributes != null ? attributes.socket : void 0;
      delete attributes.socket;
      Backbone.Model.prototype.constructor.apply(this, arguments);
    }
  });

  this.SocketIOCollection = Backbone.Collection.extend({
    constructor: function(attributes, options) {
      this.socket = attributes != null ? attributes.socket : void 0;
      delete attributes.socket;
      Backbone.Collection.prototype.constructor.apply(this, arguments);
    }
  });

}).call(this);
